/*
 * SWIFTRef API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.swiftref.java_sdk.example;

import org.junit.Ignore;
import org.junit.Test;

import com.swift.swiftref.java_sdk.ApiException;
import com.swift.swiftref.java_sdk.api.LeisApi;
import com.swift.swiftref.java_sdk.model.Bic;

/**
 * API tests for LeisApi
 */
@Ignore
public class LeisApiTest {

    private final LeisApi api = new LeisApi();

    
    /**
     * Get the BIC for an LEI
     *
     * For a given LEI, you can retrieve the BIC of that LEI.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBicFromLeiTest() throws ApiException {
    	String lei = "Example_lei";
        String xApiKey = "Example_xApiKey";
        Bic response = api.getBicFromLei(lei, xApiKey);

        System.out.println(response.toString());
    }
    
}
