/*
 * SWIFTRef API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.swift.swiftref.java_sdk.example;

import org.junit.Ignore;
import org.junit.Test;

import com.swift.swiftref.java_sdk.ApiException;
import com.swift.swiftref.java_sdk.api.NationalIdsApi;
import com.swift.swiftref.java_sdk.model.Bics;
import com.swift.swiftref.java_sdk.model.NationalIdValidity;
import com.swift.swiftref.java_sdk.model.NationalIdsDetails;

/**
 * API tests for NationalIdsApi
 */
@Ignore
public class NationalIdsApiTest {

    private final NationalIdsApi api = new NationalIdsApi();

    
    /**
     * Get BICs of a National ID
     *
     * For a given national ID, you can retrieve the BIC or the BICs of that national ID; you need to provide the national ID, and either a country code, or an indication to which scheme this national ID belongs
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBicsFromNationalIdTest() throws ApiException {
    	String nationalId = "";
        String xApiKey = "ZGyXZxU6Zmro1YZfJnJyh77IyOkKbb8n";
        String countryCode = "BE";
        String scheme = "ABB-BVB";
        Bics response = api.getBicsFromNationalId(nationalId, xApiKey, countryCode, scheme);
        System.out.println(response.toString());
    }
    
    /**
     * Get details of a National ID
     *
     * For a given National ID, you can retrieve the details of that National ID, that is the bank name or business name, and the address. You must provide either a country code, or an indication to which scheme the National ID belongs.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNationalIdDetailsTest() throws ApiException {
    	String nationalId = "CITI";
        String xApiKey = "ZGyXZxU6Zmro1YZfJnJyh77IyOkKbb8n";
        String countryCode = "BE";
        String scheme = "ABB-BVB";
        NationalIdsDetails response = api.getNationalIdDetails(nationalId, xApiKey, countryCode, scheme);
        System.out.println(response.toString());
    }
    
    /**
     * Check the Validity of a National ID
     *
     * With this API call, you can check whether a national ID is correct and valid; you need to provide the national ID, and either a country code, or an indication to which scheme this national ID belongs
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNationalIdValidityTest() throws ApiException {
    	String nationalId = "CITI";
        String xApiKey = "ZGyXZxU6Zmro1YZfJnJyh77IyOkKbb8n";
        String countryCode = "BE";
        String scheme = "ABB-BVB";
        NationalIdValidity response = api.getNationalIdValidity(nationalId, xApiKey, countryCode, scheme);
        System.out.println(response.toString());
    }
    
}
